#!/usr/bin/env ruby
require 'shellwords'


class Rush
  BUILTINS = {
    'cd' => ->(dir){ Dir.chdir(dir) },
    'exit' => ->(code = 0){ exit(code.to_i) },
    'exec' => ->(*command){ exec *command },
    'set' => ->(args){
      env_var, value = args.split('=')
      ENV[env_var] = value
    }
  }

  class << self
    def start 
      loop do
        $stdout.print 'rush> '

        line = $stdin.gets

        if line
          line.strip!
        else
          exit
        end

        command, *arguments = Shellwords.shellsplit(line)

        if cmd = BUILTINS[command]
          cmd.call(*arguments)
        else
          pid = fork {
            exec line
          }
          Process.wait pid
        end
      end
    end
  end
end

Rush.start
